const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const game=fs.readFileSync(path.join(root,'js/game.js'),'utf8');
const asset='assets/images/caballeros-submundo/caballero-demonio.webp';
const must=(name,ok)=>{if(!ok){console.error('FAIL',name);process.exitCode=1}else console.log('PASS',name)};

must('CS-001 registrado',game.includes("id:'CS-001',name:'Caballero Demonio'"));
must('familia Caballeros del Submundo',game.includes("family:'caballeros-submundo'"));
must('stats 7000/6000',game.includes("name:'Caballero Demonio',atk:7000,def:6000"));
must('rareza ancestral y nivel 10',game.includes("rarity:'ancestral',level:10"));
must('asset físico Caballero Demonio',fs.existsSync(path.join(root,asset)));
must('ruta estable del mazo',game.includes("img:'assets/images/caballeros-submundo/caballero-demonio.webp'"));
must('registro sin duplicar core',game.includes('CABALLEROS_SUBMUNDO_CARDS.forEach(c=>{if(!CARDS.some(x=>x.id===c.id))CARDS.push(c)})'));
must('Poder de los Caídos conectado al Cementerio',game.includes('function csSync()')&&game.includes('fallen*500')&&game.includes('fallen*300'));
must('Sacrificio Demoníaco operativo',game.includes("action:'demonSacrifice'")&&game.includes('await destroyCard(side,pick.i)')&&game.includes('_csSecondAttackTurn=turnNo'));
must('Heraldo evita destrucción una vez por duelo',game.includes('async function csPreventDestroy(')&&game.includes('_csHeraldUsedDuel=true')&&game.includes("if(side==='p')csQueue(side).push(returned.id)"));
must('protección conectada a destroyCard',game.includes('if(await csPreventDestroy(side,i,victim))return false'));
must('segundo ataque conectado a ambos flujos',game.includes('csKeepTurnAfterAttack(dmAttacker)')&&game.includes('csKeepTurnAfterAttack(c)'));
must('buff temporal se limpia',game.includes('function csClearTurn()')&&game.includes('c._csSacrificeAtk'));
must('colección/biblioteca reutilizada',game.includes('...CABALLEROS_SUBMUNDO_DECK_IDS]'));
must('CS-002 registrado',game.includes("id:'CS-002',name:'Caballero de Alas de Oro'"));
must('CS-002 stats supremos 10000/8500',game.includes("name:'Caballero de Alas de Oro',atk:10000,def:8500"));
must('CS-002 conserva familia del mazo',game.includes("id:'CS-002'")&&game.includes("family:'caballeros-submundo'"));
must('CS-002 crecimiento dorado por Cementerio',game.includes("gold?fallen*700:fallen*500")&&game.includes("gold?fallen*500:fallen*300"));
must('CS-002 Sentencia conectada',game.includes("action:'goldenSentence'")&&game.includes("_csUnstoppableSecondTurn=turnNo"));
must('CS-002 Resurrección Dorada conectada',game.includes("if(csIs(victim,'CS-002'))")&&game.includes("_csGoldenResUsedDuel=true")&&game.includes("victim.atk+=2000;victim.def+=2000"));
must('CS-002 Último Juicio implementado',game.includes('function csGoldenPiercingDamage(')&&game.includes('length<5')&&game.includes("toast('ÚLTIMO JUICIO: '+csPierce+' de daño perforante directo.')")&&game.includes("toast('ÚLTIMO JUICIO: el daño perforante aumenta el impacto a '+hpDiff+'.')"));
must('CS-002 ruta estable reservada',game.includes("img:'assets/images/caballeros-submundo/caballero-alas-oro.png'"));
must('CS-003 registrado',game.includes("id:'CS-003',name:'Caballero de Alas de Oro Shiny'"));
must('CS-003 stats 12500/10500',game.includes("name:'Caballero de Alas de Oro Shiny',atk:12500,def:10500"));
must('CS-003 familia correcta',game.includes("id:'CS-003'")&&game.includes("family:'caballeros-submundo'"));
must('CS-003 Shiny Suprema',game.includes("rarity:'shiny-suprema'")&&game.includes("shiny:true"));
must('CS-003 crecimiento Cementerio',game.includes("shiny?fallen*1000")&&game.includes("shiny?fallen*700"));
must('CS-003 Sentencia Suprema',game.includes("action:'shinySentence'")&&game.includes("c.atk+=2000"));
must('CS-003 Resurrección Emperador',game.includes("_csEmperorResUsedDuel=true")&&game.includes("n<3")&&game.includes("victim.atk+=3000;victim.def+=3000"));
must('CS-003 perforación desde 4 caídos',game.includes("(csIs(c,'CS-003')?4:5)"));
must('CS-003 Estado Emperador conectado',game.includes("_csEmperorUsedDuel=true")&&game.includes("_csEmperorUntil=turnNo+1")&&game.includes("c.atk+=3000;c.def+=2000")&&game.includes("_csEmperorFloorAtk")&&game.includes("ESTADO EMPERADOR: la primera destrucción rival queda NEGADA"));
must('CS-003 anti-anulación conectado',game.includes("ESTADO EMPERADOR: la anulación rival queda NEGADA")&&game.includes("delete c._strategicSkillNegatedUntil"));
must('CS-003 Estado Emperador expira',game.includes("turnNo>c._csEmperorUntil")&&game.includes("delete c._csEmperorUntil"));
must('CS-003 ruta estable',game.includes("assets/images/caballeros-submundo/caballero-alas-oro-shiny.webp"));
must('CS-004 registrado',game.includes("id:'CS-004',name:'Caballero Luz de Horus'"));
must('CS-004 stats 9500/11000',game.includes("name:'Caballero Luz de Horus',atk:9500,def:11000"));
must('CS-004 familia correcta',game.includes("id:'CS-004'")&&game.includes("family:'caballeros-submundo'"));
must('CS-004 ruta estable',game.includes("img:'assets/images/caballeros-submundo/caballero-luz-horus.webp'")&&fs.existsSync(path.join(root,'assets/images/caballeros-submundo/caballero-luz-horus.webp')));
must('CS-004 Luz de los Caídos',game.includes("horus?fallen*500")&&game.includes("horus?fallen*800"));
must('CS-004 Ojo de Horus',game.includes('function csHorusEye(')&&game.includes("reduce su efecto en 50%")&&game.includes("csHorusEye(defendedSide,target.c,sk.value)"));
must('CS-004 Luz Funeraria',game.includes("_csHorusFuneralTurn!==turnNo")&&game.includes("horusCard.atk+=1000;horusCard.def+=1000"));
must('CS-004 Juicio Sol Negro',game.includes("action:'horusJudgement'")&&game.includes("_csHorusProtectedUntil=turnNo")&&game.includes("JUICIO DEL SOL NEGRO"));
must('CS-004 Guardián Rey Caído',game.includes('function csHorusBlessResurrection(')&&game.includes("card.atk+=1500;card.def+=1500")&&game.includes("csHorusBlessResurrection(side,rev)"));
must('auditoría runtime disponible',game.includes('NEMESIS_CABALLEROS_SUBMUNDO_AUDIT'));

if(process.exitCode)process.exit(process.exitCode);
console.log('CABALLEROS DEL SUBMUNDO · CS-001: PASS');

// CS-002 final art gate trigger
