const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const must=(n,ok)=>{if(!ok){console.error('FAIL',n);process.exitCode=1}else console.log('PASS',n)};
const api=fs.readFileSync(path.join(root,'api/online1v1.js'),'utf8');
const client=fs.readFileSync(path.join(root,'js/online1v1.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
must('API online 1v1 existe',api.includes('NEMESIS ONLINE 1V1'));
must('servidor autoritativo',api.includes("authority:'server'"));
must('salas de 2 jugadores',api.includes("ROOM_FULL")&&api.includes("players.length>=2"));
must('sesion con token',api.includes('playerByToken')&&api.includes('INVALID_SESSION'));
must('heartbeat y reconexion',api.includes("action==='heartbeat'")&&client.includes('Reconectando con el núcleo online'));
must('estado versionado',api.includes('room.version=(room.version||0)+1'));
must('event log acotado',api.includes('room.events.length>120'));
must('countdown sincronizado',api.includes("room.status='COUNTDOWN'")&&api.includes("room.status='ACTIVE'"));
must('Redis Cloud oficial soportado',api.includes('REDIS_URL')&&api.includes("require('redis')"));
must('compatibilidad REST KV conservada',api.includes('KV_REST_API_URL')&&api.includes('UPSTASH_REDIS_REST_URL'));
must('produccion exige persistencia',api.includes('PERSISTENCE_REQUIRED')&&api.includes('storageReady'));
must('memoria solo desarrollo',api.includes('FLUID_MEMORY_DEV'));
must('tokens no se almacenan en claro',api.includes('tokenHash')&&!api.includes('token,seat'));
must('cliente aislado del motor',client.includes('NEMESIS_ONLINE_1V1')&&!client.includes('function battle('));
must('entrada online cargada',html.includes('js/online1v1.js'));
must('tablero Duel Master 5+5',api.includes("monsters:Array(5)")&&api.includes("supports:Array(5)"));
must('mazo Duel Master 20/20 online',api.includes("const DM_DECK=Object.keys(DM_CATALOG)")&&api.includes("'DM-020'"));
must('mano inicial 5',api.includes("hand=deck.splice(0,5)"));
must('estado rival oculta mano',api.includes("handCount:p.hand.length")&&!api.includes("opponent:{hand:"));
must('ataques autoritativos',api.includes("duelAction==='attack'")&&api.includes("NOT_YOUR_TURN"));
must('cliente renderiza arena avanzada multideck',client.includes('renderDuelMasterBoard')&&client.includes('ONLINE MULTIMAZO'));
must('zonas soporte y monstruo cliente',client.includes('dmSupportZones')&&client.includes('dmMonsterZones'));
must('20/20 efectos autoritativos declarados',api.includes('DM_EFFECT_HANDLERS')&&api.includes("Object.fromEntries(DM_DECK.map(id=>[id,true]))"));
must('habilidades Duel Master en servidor',api.includes('resolveDmAbility')&&api.includes("duelAction==='ability'")&&api.includes("duelAction==='ultimate'"));
must('equipamiento Duel Master en servidor',api.includes('equipSupport')&&api.includes("'DM-013','DM-014','DM-015','DM-016','DM-017'"));
must('trampas respuesta servidor',api.includes('tryHunterTrap')&&api.includes('tryTitanTrap'));
must('transformación Thor Shiny servidor',api.includes('tryShinyAwakening')&&api.includes("p.monsters[thor]='DM-018'"));
must('Zeus negate autoritativo',api.includes('tryZeusNegate')&&api.includes('ZEUS_NEGATE'));
must('Eclipse de los Reinos servidor',api.includes('ECLIPSE_REALMS')&&api.includes("id==='DM-020'"));
must('cliente controla habilidad ultimate soporte',client.includes('dmAbility')&&client.includes('dmUltimate')&&client.includes('dmSupportActivate'));
must('cliente envía mazo activo',client.includes('activeDeckPayload')&&client.includes('deckName')&&client.includes('deckIds'));
must('servidor registra mazo por jugador',api.includes('playerDeckMeta')&&api.includes('deckClass'));
must('servidor usa composición real validada',api.includes("requested=cleanDeckIds(b.deckIds)")&&api.includes("requested.some(id=>!allowed.has(id))")&&api.includes("meta?.deckIds")&&api.includes("ONLINE_DECK_INVALID_CARD"));
must('online reconoce cinco mazos oficiales',api.includes("'MAGO_ROJO'")&&api.includes("'IMPERIO_DRAGON'")&&api.includes("'OLIMPO'")&&api.includes("'CABALLEROS_SUBMUNDO'"));
const ownerApi=fs.readFileSync(path.join(root,'api/owner-auth.js'),'utf8');
const ownerLib=fs.readFileSync(path.join(root,'lib/owner-auth.js'),'utf8');
const ownerClient=fs.readFileSync(path.join(root,'js/owner-auth.js'),'utf8');
must('autenticación real propietario con HMAC y cookie HttpOnly',ownerLib.includes("createHmac('sha256'")&&ownerLib.includes('HttpOnly')&&ownerApi.includes("action==='login'")&&api.includes("ownerAuth.verifyRequest(req)"));
must('secreto propietario no viaja por cliente online',!client.includes('nemesis_owner_token_v1')&&!client.includes('ownerToken=')&&ownerClient.includes("/api/owner-auth"));
must('motor multideck autoritativo',api.includes("mode:'MULTI_DECK'")&&api.includes('ONLINE_EFFECT_HANDLERS'));
must('Mago Rojo 20/20 online',api.includes('MGR_CATALOG')&&api.includes('resolveMgrAbility')&&api.includes('resolveMgrSupport')&&api.includes('MGR_MIRROR')&&api.includes('GRIMORIO_NEGATE'));
must('Imperio Dragón 20/20 online',api.includes('IDR_CATALOG')&&api.includes('resolveIdrAbility')&&api.includes('resolveIdrSupport')&&api.includes('IDR_TRANSFORM')&&api.includes('IDR_FUSION'));
must('Olimpo 11/11 online',api.includes('OLIMPO_CATALOG')&&api.includes('resolveOlimpoAbility')&&api.includes('resolveOlimpoSupport')&&api.includes('OLYMPUS_FUSION'));
must('Caballeros 20/20 online',api.includes('CS_CATALOG')&&api.includes('resolveCsAbility')&&api.includes('resolveCsSupport')&&api.includes('CS_UNDERWORLD_RAY'));
must('armaduras visibles y persistentes online',api.includes("equipment:{weapon:null,armor:null,relic:null}")&&client.includes('eq.armor'));
must('auditoría online cinco motores',api.includes('onlineEngineAudit')&&api.includes("action==='engine_audit'"));
if(process.exitCode)process.exit(process.exitCode);
console.log('NÉMESIS ONLINE 1V1 BASE: PASS');
