const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const must=(n,ok)=>{if(!ok){console.error('FAIL',n);process.exitCode=1}else console.log('PASS',n)};
const api=fs.readFileSync(path.join(root,'api/online1v1.js'),'utf8');
const client=fs.readFileSync(path.join(root,'js/online1v1.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
must('API online 1v1 existe',api.includes('NEMESIS ONLINE 1V1'));
must('servidor autoritativo',api.includes("authority:'server'"));
must('salas de 2 jugadores',api.includes("ROOM_FULL")&&api.includes("players.length>=2"));
must('sesion con token',api.includes('playerByToken')&&api.includes('INVALID_SESSION'));
must('heartbeat y reconexion',api.includes("action==='heartbeat'")&&client.includes('Reconectando con el núcleo online'));
must('estado versionado',api.includes('room.version=(room.version||0)+1'));
must('event log acotado',api.includes('room.events.length>120'));
must('countdown sincronizado',api.includes("room.status='COUNTDOWN'")&&api.includes("room.status='ACTIVE'"));
must('storage cloud preparado',api.includes('KV_REST_API_URL')&&api.includes('UPSTASH_REDIS_REST_URL'));
must('fallback fluid memory',api.includes('FLUID_MEMORY'));
must('cliente aislado del motor',client.includes('NEMESIS_ONLINE_1V1')&&!client.includes('function battle('));
must('entrada online cargada',html.includes('js/online1v1.js'));
if(process.exitCode)process.exit(process.exitCode);
console.log('NÉMESIS ONLINE 1V1 BASE: PASS');
