const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const must=(n,ok)=>{if(!ok){console.error('FAIL',n);process.exitCode=1}else console.log('PASS',n)};
const api=fs.readFileSync(path.join(root,'api/online1v1.js'),'utf8');
const client=fs.readFileSync(path.join(root,'js/online1v1.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
must('API online 1v1 existe',api.includes('NEMESIS ONLINE 1V1'));
must('servidor autoritativo',api.includes("authority:'server'"));
must('salas de 2 jugadores',api.includes("ROOM_FULL")&&api.includes("players.length>=2"));
must('sesion con token',api.includes('playerByToken')&&api.includes('INVALID_SESSION'));
must('heartbeat y reconexion',api.includes("action==='heartbeat'")&&client.includes('Reconectando con el núcleo online'));
must('estado versionado',api.includes('room.version=(room.version||0)+1'));
must('event log acotado',api.includes('room.events.length>120'));
must('countdown sincronizado',api.includes("room.status='COUNTDOWN'")&&api.includes("room.status='ACTIVE'"));
must('Redis Cloud oficial soportado',api.includes('REDIS_URL')&&api.includes("require('redis')"));
must('compatibilidad REST KV conservada',api.includes('KV_REST_API_URL')&&api.includes('UPSTASH_REDIS_REST_URL'));
must('produccion exige persistencia',api.includes('PERSISTENCE_REQUIRED')&&api.includes('storageReady'));
must('memoria solo desarrollo',api.includes('FLUID_MEMORY_DEV'));
must('tokens no se almacenan en claro',api.includes('tokenHash')&&!api.includes('token,seat'));
must('cliente aislado del motor',client.includes('NEMESIS_ONLINE_1V1')&&!client.includes('function battle('));
must('entrada online cargada',html.includes('js/online1v1.js'));
must('tablero Duel Master 5+5',api.includes("monsters:Array(5)")&&api.includes("supports:Array(5)"));
must('mazo Duel Master 20/20 online',api.includes("const DM_DECK=Object.keys(DM_CATALOG)")&&api.includes("'DM-020'"));
must('mano inicial 5',api.includes("hand=deck.splice(0,5)"));
must('estado rival oculta mano',api.includes("handCount:p.hand.length")&&!api.includes("opponent:{hand:"));
must('ataques autoritativos',api.includes("duelAction==='attack'")&&api.includes("NOT_YOUR_TURN"));
must('cliente renderiza arena avanzada',client.includes('renderDuelMasterBoard')&&client.includes('DUEL MASTER ONLINE'));
must('zonas soporte y monstruo cliente',client.includes('dmSupportZones')&&client.includes('dmMonsterZones'));
must('20/20 efectos autoritativos declarados',api.includes('DM_EFFECT_HANDLERS')&&api.includes("Object.fromEntries(DM_DECK.map(id=>[id,true]))"));
must('habilidades Duel Master en servidor',api.includes('resolveDmAbility')&&api.includes("duelAction==='ability'")&&api.includes("duelAction==='ultimate'"));
must('equipamiento Duel Master en servidor',api.includes('equipSupport')&&api.includes("'DM-013','DM-014','DM-015','DM-016','DM-017'"));
must('trampas respuesta servidor',api.includes('tryHunterTrap')&&api.includes('tryTitanTrap'));
must('transformación Thor Shiny servidor',api.includes('tryShinyAwakening')&&api.includes("p.monsters[thor]='DM-018'"));
must('Zeus negate autoritativo',api.includes('tryZeusNegate')&&api.includes('ZEUS_NEGATE'));
must('Eclipse de los Reinos servidor',api.includes('ECLIPSE_REALMS')&&api.includes("id==='DM-020'"));
must('cliente controla habilidad ultimate soporte',client.includes('dmAbility')&&client.includes('dmUltimate')&&client.includes('dmSupportActivate'));
if(process.exitCode)process.exit(process.exitCode);
console.log('NÉMESIS ONLINE 1V1 BASE: PASS');
