import{FrozenDataLoader,DataRepository,CardRegistry,DeckRegistry,registerMagoRojo,registerImperioDragon,DuelSession,AssetResolver,buildCardViewModel,CardRenderer,RendererGuard}from'../src/index.js';
let duel,cards,decks,data,started=false;const summary=document.getElementById('duel-summary');const renderer=new CardRenderer({placeholder:'../public/assets/placeholder.svg'}),guard=new RendererGuard();
const map={};for(const prefix of['MGR','IDR'])for(let i=1;i<=20;i++){const id=prefix+'-'+String(i).padStart(3,'0');map[id]='../public/assets/cards/'+id+'.svg'}const resolver=new AssetResolver({map,placeholder:'../public/assets/placeholder.svg'});
async function boot(){data=new DataRepository(await FrozenDataLoader.browser().loadAll());cards=new CardRegistry();decks=new DeckRegistry();registerMagoRojo({dataRepository:data,cardRegistry:cards,deckRegistry:decks});registerImperioDragon({dataRepository:data,cardRegistry:cards,deckRegistry:decks});let n=0;duel=new DuelSession({cardRegistry:cards,deckRegistry:decks,players:['player','enemy'],uidFactory:(d,c)=>'duel-'+(++n)+'-'+c});duel.prepareDeck('player','MAGO_ROJO');duel.prepareDeck('enemy','IMPERIO_DRAGON');started=false;draw('PREPARADO · 40 UID')}
function cardMini(inst){const host=document.createElement('div'),def=cards.get(inst.cardId),vm=buildCardViewModel({definition:def,instance:inst,imageUrl:resolver.resolve(def)});guard.render(renderer,vm,host);return host}
function zone(owner,hostId){const host=document.getElementById(hostId);host.replaceChildren();const session=duel.decks.session(owner);for(const uid of session.uids){const c=duel.state.instances.get(uid);if(c.zone==='hand')host.appendChild(cardMini(c))}}
function draw(label){if(!duel)return;zone('player','player-zone');zone('enemy','enemy-zone');const t=duel.turns.snapshot();summary.textContent=label+'\nTURNO='+t.turnNumber+' · ACTIVO='+(t.currentPlayer||'—')+'\nMAGO deck='+duel.decks.count('player','deck')+' mano='+duel.decks.count('player','hand')+'\nIMPERIO deck='+duel.decks.count('enemy','deck')+' mano='+duel.decks.count('enemy','hand')+'\nINSTANCIAS='+duel.state.instances.size+' · UID ÚNICOS='+new Set(duel.state.instances.keys()).size+'\n'+JSON.stringify(duel.state.audit(),null,2)}
document.getElementById('start').onclick=()=>{if(started)return;duel.start({firstPlayer:'player',openingHandSize:5});started=true;draw('DUELO INICIADO · MANOS 5/5')};
document.getElementById('draw').onclick=()=>{if(!started)return;const p=duel.turns.currentPlayer;duel.drawForTurn(p,1);draw('ROBO DE TURNO · '+p)};
document.getElementById('end').onclick=()=>{if(!started)return;const p=duel.turns.currentPlayer;duel.endTurn(p);draw('FIN DE TURNO · AHORA '+duel.turns.currentPlayer)};
document.getElementById('reset').onclick=boot;boot();