import{FrozenDataLoader,DataRepository,CardRegistry,DeckRegistry,registerMagoRojo,registerImperioDragon,DuelSession,AssetResolver,buildCardViewModel,CardRenderer,RendererGuard}from'../src/index.js';
let duel,cards,decks,data,started=false,pendingPermit=null;const summary=document.getElementById('duel-summary');const renderer=new CardRenderer({placeholder:'../public/assets/placeholder.svg'}),guard=new RendererGuard();
const map={};for(const prefix of['MGR','IDR'])for(let i=1;i<=20;i++){const id=prefix+'-'+String(i).padStart(3,'0');map[id]='../public/assets/cards/'+id+'.svg'}const resolver=new AssetResolver({map,placeholder:'../public/assets/placeholder.svg'});
async function boot(){data=new DataRepository(await FrozenDataLoader.browser().loadAll());cards=new CardRegistry();decks=new DeckRegistry();registerMagoRojo({dataRepository:data,cardRegistry:cards,deckRegistry:decks});registerImperioDragon({dataRepository:data,cardRegistry:cards,deckRegistry:decks});let n=0;duel=new DuelSession({cardRegistry:cards,deckRegistry:decks,players:['player','enemy'],uidFactory:(d,c)=>'duel-'+(++n)+'-'+c,monsterZoneLimit:5});duel.prepareDeck('player','MAGO_ROJO');duel.prepareDeck('enemy','IMPERIO_DRAGON');started=false;pendingPermit=null;renderAll('PREPARADO · 40 UID')}
function cardMini(inst){const host=document.createElement('div'),def=cards.get(inst.cardId),vm=buildCardViewModel({definition:def,instance:inst,imageUrl:resolver.resolve(def)});guard.render(renderer,vm,host);return host}
function renderZone(owner,zone,hostId){const host=document.getElementById(hostId);host.replaceChildren();const session=duel.decks.session(owner);for(const uid of session.uids){const c=duel.state.instances.get(uid);if(c.zone===zone)host.appendChild(cardMini(c))}}
function active(){return duel?.turns?.currentPlayer}
function summonableHand(player){return duel.decks.session(player).uids.map(uid=>duel.state.instances.get(uid)).filter(c=>c.zone==='hand'&&cards.get(c.cardId)?.type==='CRIATURA')}
function renderAll(label){if(!duel)return;renderZone('player','hand','player-hand');renderZone('player','field','player-field');renderZone('enemy','hand','enemy-hand');renderZone('enemy','field','enemy-field');const t=duel.turns.snapshot(),ph=duel.phases.snapshot();summary.textContent=label+'\nTURNO='+t.turnNumber+' · ACTIVO='+(t.currentPlayer||'—')+' · FASE='+(ph.phase||'—')+'\nMAGO deck='+duel.decks.count('player','deck')+' mano='+duel.decks.count('player','hand')+' campo='+duel.decks.count('player','field')+'\nIMPERIO deck='+duel.decks.count('enemy','deck')+' mano='+duel.decks.count('enemy','hand')+' campo='+duel.decks.count('enemy','field')+'\nINSTANCIAS='+duel.state.instances.size+' · UID ÚNICOS='+new Set(duel.state.instances.keys()).size+'\nPERMISO ESPECIAL='+(pendingPermit?pendingPermit.uid:'—')+'\n'+JSON.stringify(duel.state.audit(),null,2)}
function run(fn){try{fn()}catch(e){renderAll('BLOQUEADO: '+e.message)}}
document.getElementById('start').onclick=()=>run(()=>{if(started)return;duel.start({firstPlayer:'player',openingHandSize:5});started=true;renderAll('DUELO INICIADO · DRAW · MANOS 5/5')});
document.getElementById('draw').onclick=()=>run(()=>{const p=active();const c=duel.drawForTurn(p)[0];renderAll('ROBO DE TURNO · '+p+' · '+(c?.cardId||'SIN CARTA'))});
document.getElementById('phase').onclick=()=>run(()=>{const p=active();const ph=duel.advancePhase(p);renderAll('FASE -> '+ph.phase)});
document.getElementById('normal').onclick=()=>run(()=>{const p=active(),c=summonableHand(p)[0];if(!c)throw new Error('NO_SUMMONABLE_CREATURE_IN_HAND');const before=c.uid;duel.normalSummon(p,c.uid);renderAll('NORMAL · '+c.cardId+' · UID '+before+' CONSERVADO')});
document.getElementById('special-auth').onclick=()=>run(()=>{const p=active(),c=summonableHand(p)[0];if(!c)throw new Error('NO_SUMMONABLE_CREATURE_IN_HAND');pendingPermit=duel.authorizeSpecialSummon({player:p,uid:c.uid,source:'LAB_AUTHORIZED_EFFECT'});renderAll('PERMISO ESPECIAL EMITIDO · '+c.cardId+' · '+c.uid)});
document.getElementById('special').onclick=()=>run(()=>{if(!pendingPermit)throw new Error('NO_PENDING_SPECIAL_PERMIT');const p=active(),uid=pendingPermit.uid,c=duel.state.instances.get(uid);duel.specialSummon(p,uid,pendingPermit);pendingPermit=null;renderAll('ESPECIAL · '+c.cardId+' · UID '+uid+' CONSERVADO')});
document.getElementById('end').onclick=()=>run(()=>{const p=active();const x=duel.endTurn(p);pendingPermit=null;renderAll('FIN DE TURNO · AHORA '+x.turn.currentPlayer+' · '+x.phase.phase)});
document.getElementById('reset').onclick=boot;boot();