import{CardRegistry}from'../src/core/CardRegistry.js';import{createCardInstance}from'../src/core/CardInstance.js';import{GameState}from'../src/core/GameState.js';import{GraveyardService}from'../src/services/GraveyardService.js';import{AssetResolver}from'../src/assets/AssetResolver.js';import{buildCardViewModel}from'../src/viewmodel/CardViewModel.js';import{CardRenderer}from'../src/renderer/CardRenderer.js';import{RendererGuard}from'../src/renderer/RendererGuard.js';
const defs=[{id:'MGR-001',name:'Mago Rojo',atk:2800,def:2400,type:'CRIATURA',rarity:'EPICA'},{id:'IDR-001',name:'Dragón Carmesí Joven',atk:1800,def:1600,type:'CRIATURA',rarity:'COMUN'}];
const reg=new CardRegistry();defs.forEach(x=>reg.register(x));
const resolver=new AssetResolver({map:{'MGR-001':'../public/assets/cards/MGR-001.svg','IDR-001':'../public/assets/cards/IDR-001.svg'},placeholder:'../public/assets/placeholder.svg'});
const renderer=new CardRenderer({placeholder:'../public/assets/placeholder.svg'});
const guard=new RendererGuard({onError:(e,ctx)=>write('RENDER ERROR AISLADO: '+e.message+' · UID '+ctx.uid)});
const order=['deck','hand','field','graveyard','field'];let state,instances,step,grave;
function boot(){state=new GameState();instances=[createCardInstance('MGR-001',{uid:'lab-mgr-001-copy-1'}),createCardInstance('IDR-001',{uid:'lab-idr-001-copy-1'})];instances.forEach(x=>state.add(x,'deck'));grave=new GraveyardService(state);step=0;draw('BOOT')}
function vmFor(inst){const def=reg.get(inst.cardId);return buildCardViewModel({definition:def,instance:inst,imageUrl:resolver.resolve(def)})}
function draw(event){instances.forEach((inst,i)=>{const vm=vmFor(inst);guard.render(renderer,vm,document.getElementById(i?'card-b':'card-a'));document.getElementById(i?'uid-b':'uid-a').textContent='UID '+vm.uid+' · ZONA '+vm.zone+' · IMG '+vm.imageUrl});write(event)}
function write(event){document.getElementById('log').textContent=event+'\n'+JSON.stringify(state.audit(),null,2)+'\nMGR UID='+instances?.[0]?.uid+' ZONA='+instances?.[0]?.zone}
document.getElementById('next').onclick=()=>{if(step>=order.length-1)return;step++;instances.forEach(x=>state.move(x.uid,order[step]));draw('MOVE -> '+order[step].toUpperCase())};
document.getElementById('destroy').onclick=()=>{const c=instances[0];if(c.zone!=='field'){write('DESTRUCCIÓN BLOQUEADA: MGR-001 debe estar en FIELD');return}grave.destroy(c.uid,{reason:'lab'});draw('DESTRUIDA -> GRAVEYARD · UID CONSERVADO')};
document.getElementById('resurrect').onclick=()=>{const c=instances[0];if(c.zone!=='graveyard'){write('RESURRECCIÓN BLOQUEADA: MGR-001 debe estar en GRAVEYARD');return}grave.resurrect(c.uid);draw('RESUCITADA -> FIELD · MISMO UID')};
document.getElementById('fail-renderer').onclick=()=>{const c=instances[0],vm=vmFor(c),before=c.uid+'|'+c.zone;const result=guard.render({render(){throw new Error('INTENTIONAL_RENDER_FAILURE')}},vm,document.getElementById('card-a'));const after=c.uid+'|'+c.zone;write('FALLO VISUAL: '+(result.ok?'NO':'CAPTURADO')+' · ESTADO '+(before===after?'INTACTO':'ALTERADO'));setTimeout(()=>draw('RENDER RECUPERADO · CARTA NUNCA SALIÓ DEL GAMESTATE'),450)};
document.getElementById('break-image').onclick=()=>{const c=instances[0],before=c.uid+'|'+c.zone;const img=document.querySelector('#card-a .clean-card__image');if(img){img.src='../public/assets/cards/NO-EXISTE.svg';setTimeout(()=>{const after=c.uid+'|'+c.zone;write('IMAGEN ROTA -> PLACEHOLDER · ESTADO '+(before===after?'INTACTO':'ALTERADO'))},250)}};\ndocument.getElementById('reset').onclick=boot;boot();