import assert from'node:assert/strict';
import fs from'node:fs/promises';import path from'node:path';import{fileURLToPath}from'node:url';
import{FrozenDataLoader,DataRepository,CardRegistry,DeckRegistry,registerMagoRojo,registerImperioDragon,DuelSession}from'../src/index.js';
const here=path.dirname(fileURLToPath(import.meta.url)),repoRoot=path.resolve(here,'../..');let pass=0;
const ok=(x,m)=>{assert.ok(x,m);pass++};const fails=(fn,part,m)=>{let e=null;try{fn()}catch(err){e=err}ok(!!e&&String(e.message).includes(part),m)};
const readJson=async p=>JSON.parse(await fs.readFile(path.join(repoRoot,p),'utf8'));
const data=new DataRepository(await new FrozenDataLoader({readJson}).loadAll()),cards=new CardRegistry(),decks=new DeckRegistry();
registerMagoRojo({dataRepository:data,cardRegistry:cards,deckRegistry:decks});registerImperioDragon({dataRepository:data,cardRegistry:cards,deckRegistry:decks});
let n=0;const duel=new DuelSession({cardRegistry:cards,deckRegistry:decks,players:['player','enemy'],uidFactory:(d,c)=>'cmb-'+(++n)+'-'+c,monsterZoneLimit:5,startingHp:4000});
duel.prepareDeck('player','MAGO_ROJO');duel.prepareDeck('enemy','IMPERIO_DRAGON');duel.start({firstPlayer:'player',openingHandSize:20});
duel.drawForTurn('player');duel.advancePhase('player');
const pHand=duel.decks.session('player').uids.map(uid=>duel.state.instances.get(uid)).filter(c=>c.zone==='hand');
const eHand=duel.decks.session('enemy').uids.map(uid=>duel.state.instances.get(uid)).filter(c=>c.zone==='hand');
const atk=pHand.find(c=>c.cardId==='MGR-001'),def=eHand.find(c=>c.cardId==='IDR-001');
duel.normalSummon('player',atk.uid);const permit=duel.authorizeSpecialSummon({player:'player',uid:pHand.find(c=>c.cardId==='MGR-002').uid,source:'TEST'});duel.specialSummon('player',permit.uid,permit);
fails(()=>duel.attack('player',atk.uid,def.uid),'BATTLE_REQUIRES_FIELD','target must be on field');
for(const p of ['BATTLE'])duel.advancePhase('player');
const ePermit=duel.actions.authorizeSpecialSummon.bind(duel.actions);
fails(()=>ePermit({player:'enemy',uid:def.uid,source:'TEST'}),'NO_TURN_PRIORITY','enemy cannot summon out of turn');
duel.state.move(def.uid,'field');
const baseA=cards.get('MGR-001').atk,baseD=cards.get('IDR-001').def;
const r1=duel.attack('player',atk.uid,def.uid);
ok(r1.outcome==='ATTACKER_WINS','attacker wins when ATK > DEF');
ok(r1.damage===1200&&r1.damagedPlayer==='enemy','damage equals ATK minus DEF');
ok(def.zone==='graveyard','destroyed defender moved to graveyard');
ok(atk.zone==='field','attacker remains on field');
ok(duel.hp.enemy===2800,'enemy HP reduced');
ok(cards.get('MGR-001').atk===baseA&&cards.get('IDR-001').def===baseD,'base stats unchanged');
ok(duel.state.audit().ok,'state valid after battle');
fails(()=>duel.attack('player',atk.uid,pHand.find(c=>c.cardId==='MGR-002').uid),'TARGET_MUST_BE_OPPONENT','own target blocked');
fails(()=>duel.attack('player',atk.uid,atk.uid),'ATTACK_TARGET_MUST_DIFFER','self target blocked');
fails(()=>duel.attack('player',atk.uid,def.uid),'BATTLE_REQUIRES_FIELD','graveyard target blocked');

const duel2=new DuelSession({cardRegistry:cards,deckRegistry:decks,players:['p','e'],uidFactory:(d,c)=>'cmb2-'+(++n)+'-'+c,startingHp:1000});
duel2.prepareDeck('p','MAGO_ROJO');duel2.prepareDeck('e','IMPERIO_DRAGON');duel2.start({firstPlayer:'p',openingHandSize:20});duel2.drawForTurn('p');duel2.advancePhase('p');
const ph=duel2.decks.session('p').uids.map(uid=>duel2.state.instances.get(uid)).filter(c=>c.zone==='hand'),eh=duel2.decks.session('e').uids.map(uid=>duel2.state.instances.get(uid)).filter(c=>c.zone==='hand');
const pa=ph.find(c=>c.cardId==='MGR-001'),ed=eh.find(c=>c.cardId==='IDR-001');duel2.normalSummon('p',pa.uid);duel2.state.move(ed.uid,'field');duel2.advancePhase('p');
const win=duel2.attack('p',pa.uid,ed.uid);
ok(win.victory?.winner==='p','victory triggered at HP zero');
ok(duel2.hp.e===0,'HP clamps to zero');
fails(()=>duel2.attack('p',pa.uid,ed.uid),'DUEL_ALREADY_FINISHED','attack blocked after victory');
fails(()=>duel2.endTurn('p'),'DUEL_ALREADY_FINISHED','turn cannot continue after victory');
ok(duel2.state.audit().ok,'victory state valid');

console.log('NEMESIS RUNTIME CLEAN COMBAT: PASS — '+pass+'/'+pass);